# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.TextField()),
                ('tipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('actividad', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('requisitos', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=7, verbose_name='INACTIVO')),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='eventos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.Tipos'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.Eventos'),
        ),
    ]
